'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Pacientes', [
      {
        id: 1,
        codigo: 'PAC001',
        nome: 'João Silva',
        email: 'joao@email.com',
        dataNascimento: new Date('1991-11-13'),
        sexo: 'Masculino',
        obs: null,
        estadoCivil: 'Casado(a)',
        nacionalidade: 'Brasileiro',
        naturalidade: 'São Paulo',
        estado: 'SP',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 1,
        createdAt: new Date('2025-04-18T02:12:48'),
        updatedAt: new Date('2025-04-19T02:48:44')
      },
      {
        id: 2,
        codigo: 'PAC002',
        nome: 'João josé',
        email: 'joao2@email.com',
        dataNascimento: new Date('1990-01-01'),
        sexo: 'Masculino',
        obs: null,
        estadoCivil: 'Solteiro(a)',
        nacionalidade: 'Brasileiro',
        naturalidade: 'Rio de Janeiro',
        estado: 'RJ',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 1,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-19T02:49:11')
      },
      {
        id: 3,
        codigo: 'PAC003',
        nome: 'Maria Souza',
        email: 'maria@email.com',
        dataNascimento: new Date('1985-05-20'),
        sexo: 'Feminino',
        obs: null,
        estadoCivil: 'Divorciado(a)',
        nacionalidade: 'Brasileira',
        naturalidade: 'Belo Horizonte',
        estado: 'MG',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 2,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 4,
        codigo: 'PAC004',
        nome: 'Ana Paula',
        email: 'anapaula@email.com',
        dataNascimento: new Date('1984-04-15'),
        sexo: 'Feminino',
        obs: null,
        estadoCivil: 'Casado(a)',
        nacionalidade: 'Brasileira',
        naturalidade: 'Salvador',
        estado: 'BA',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 2,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 5,
        codigo: 'PAC005',
        nome: 'Carlos Eduardo',
        email: 'carloseduardo@email.com',
        dataNascimento: new Date('1985-02-15'),
        sexo: 'Feminino',
        obs: null,
        estadoCivil: 'Solteiro(a)',
        nacionalidade: 'Brasileiro',
        naturalidade: 'Curitiba',
        estado: 'PR',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 2,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 6,
        codigo: 'PAC006',
        nome: 'Fernanda Lima',
        email: 'fernandalima@email.com',
        dataNascimento: new Date('1986-05-15'),
        sexo: 'Masculino',
        obs: null,
        estadoCivil: 'Casado(a)',
        nacionalidade: 'Brasileiro',
        naturalidade: 'Porto Alegre',
        estado: 'RS',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 2,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 7,
        codigo: 'PAC007',
        nome: 'Roberto Carlos',
        email: 'robertocarlos@email.com',
        dataNascimento: new Date('1987-04-15'),
        sexo: 'Feminino',
        obs: null,
        estadoCivil: 'Solteiro(a)',
        nacionalidade: 'Brasileiro',
        naturalidade: 'Campinas',
        estado: 'SP',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 1,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 8,
        codigo: 'PAC008',
        nome: 'Juliana Mendes',
        email: 'julianamendes@email.com',
        dataNascimento: new Date('1988-08-15'),
        sexo: 'Feminino',
        obs: null,
        estadoCivil: 'Viúvo(a)',
        nacionalidade: 'Brasileira',
        naturalidade: 'Salvador',
        estado: 'BA',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 2,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 9,
        codigo: 'PAC009',
        nome: 'Paulo César',
        email: 'paulocésar@email.com',
        dataNascimento: new Date('1989-06-15'),
        sexo: 'Feminino',
        obs: null,
        estadoCivil: 'Solteiro(a)',
        nacionalidade: 'Brasileira',
        naturalidade: 'Uberlândia',
        estado: 'MG',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 1,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 10,
        codigo: 'PAC010',
        nome: 'Camila Alves',
        email: 'camilaalves@email.com',
        dataNascimento: new Date('1980-02-15'),
        sexo: 'Masculino',
        obs: null,
        estadoCivil: 'Casado(a)',
        nacionalidade: 'Brasileiro',
        naturalidade: 'Niterói',
        estado: 'RJ',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 2,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 11,
        codigo: 'PAC011',
        nome: 'Ricardo Gomes',
        email: 'ricardogomes@email.com',
        dataNascimento: new Date('1981-09-15'),
        sexo: 'Masculino',
        obs: null,
        estadoCivil: 'Divorciado(a)',
        nacionalidade: 'Brasileira',
        naturalidade: 'Florianópolis',
        estado: 'SC',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 2,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 12,
        codigo: 'PAC012',
        nome: 'Larissa Souza',
        email: 'larissasouza@email.com',
        dataNascimento: new Date('1982-07-15'),
        sexo: 'Feminino',
        obs: null,
        estadoCivil: 'Solteiro(a)',
        nacionalidade: 'Brasileira',
        naturalidade: 'Goiânia',
        estado: 'GO',
        dataEntrada: new Date('2025-04-18'),
        registeredBy: 1,
        createdAt: new Date('2025-04-18T22:48:02'),
        updatedAt: new Date('2025-04-18T22:48:02')
      },
      {
        id: 31,
        codigo: 'pac001',
        nome: 'CLEVER SANTORO LOPES',
        email: 'cleversantoro@hotmail.com',
        dataNascimento: new Date('1970-10-11'),
        sexo: 'Masculino',
        obs: null,
        estadoCivil: 'Solteiro(a)',
        nacionalidade: 'brasileiro',
        naturalidade: 'Álvares Machado',
        estado: 'SP',
        dataEntrada: new Date('2025-04-30'),
        registeredBy: 1,
        createdAt: new Date('2025-04-28T03:50:34'),
        updatedAt: new Date('2025-04-28T03:50:34')
      }
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Pacientes', {
      id: { [Sequelize.Op.in]: [1,2,3,4,5,6,7,8,9,10,11,12,31] }
    }, {});
  }
};
